-- ============================================================
-- Quest — migration 0013: biblioteca viva de exercicios (v8) — 59 exercicios
-- ------------------------------------------------------------
-- Banco consultavel com ficha detalhada (musculos, execucao, cue, erro comum,
-- variacoes), grupo/padrao/equipamento, casa_ok e peso_esforco_base. Leitura p/
-- autenticados. Expansivel. ON CONFLICT DO NOTHING (idempotente).
-- ============================================================

create table if not exists public.exercicios (
  id                 text primary key,
  nome               text not null,
  grupo_muscular     text not null,
  padrao_movimento   text,
  equipamento        text,
  musculos           jsonb,
  execucao           text,
  cue                text,
  erro_comum         text,
  variacoes          jsonb,
  peso_esforco_base  numeric not null default 1,
  casa_ok            boolean not null default false
);

alter table public.exercicios enable row level security;
drop policy if exists exercicios_select on public.exercicios;
create policy exercicios_select on public.exercicios for select using (auth.role() = 'authenticated');

insert into public.exercicios (id,nome,grupo_muscular,padrao_movimento,equipamento,musculos,execucao,cue,erro_comum,variacoes,peso_esforco_base,casa_ok) values
('ex_supino_reto_com_barra','Supino reto com barra','peito','empurrar horizontal','barra','["peitoral maior","tríceps","deltoide anterior"]'::jsonb,'Deite no banco, pegada pouco além dos ombros, desça a barra até o meio do peito e empurre.','Escápulas retraídas e pés firmes; barra desce controlada.','Saltar o peito / abrir demais os cotovelos.','["Supino inclinado","Supino declinado","Supino pegada fechada"]'::jsonb,1.3,false),
('ex_supino_inclinado_com_barra','Supino inclinado com barra','peito','empurrar horizontal','barra','["peitoral superior","deltoide anterior","tríceps"]'::jsonb,'Banco a 30–45°, desça a barra até a clavícula alta e empurre.','Foco na parte alta do peito; cotovelos ~45°.','Inclinar demais (vira ombro).','["Supino inclinado com halteres","Máquina inclinada"]'::jsonb,1.3,false),
('ex_supino_inclinado_com_halteres','Supino inclinado com halteres','peito','empurrar horizontal','halter','["peitoral superior","deltoide anterior"]'::jsonb,'Banco inclinado, halteres na linha do peito alto, empurre juntando levemente em cima.','Amplitude maior que a barra; controla a descida.','Bater os halteres no topo e perder tensão.','["Supino reto halteres","Crucifixo inclinado"]'::jsonb,1.2,false),
('ex_crucifixo_com_halteres','Crucifixo com halteres','peito','isolado','halter','["peitoral maior"]'::jsonb,'Deitado, braços semiflexionados, abra em arco e junte sem estender total.','Arco fixo; sente o alongamento do peito.','Transformar em supino dobrando o cotovelo.','["Crucifixo inclinado","Crossover"]'::jsonb,0.9,false),
('ex_crossover_na_polia','Crossover na polia','peito','isolado','cabo','["peitoral maior","peitoral inferior"]'::jsonb,'Polias altas, passo à frente, junte as mãos à frente do quadril.','Contrai o peito no final; tronco levemente à frente.','Usar impulso do corpo.','["Crossover baixo→alto","Crucifixo na polia"]'::jsonb,0.9,false),
('ex_flexao_de_braco','Flexão de braço','peito','empurrar horizontal','peso corporal','["peitoral","tríceps","core"]'::jsonb,'Mãos na largura do peito, corpo reto, desça o peito ao chão e empurre.','Abdômen firme; corpo em prancha.','Cair o quadril / não descer.','["Flexão inclinada","Flexão declinada","Flexão diamante"]'::jsonb,1,true),
('ex_supino_maquina','Supino máquina','peito','empurrar horizontal','maquina','["peitoral","tríceps"]'::jsonb,'Ajuste o banco, pegada na linha do peito, empurre sem travar o cotovelo.','Ótimo pra volume seguro e falha.','Selim alto demais (vira ombro).','["Máquina inclinada","Peck deck"]'::jsonb,1.1,false),
('ex_peck_deck_voador','Peck deck (voador)','peito','isolado','maquina','["peitoral maior"]'::jsonb,'Sentado, cotovelos na almofada, junte à frente contraindo o peito.','Isola o peito; segura 1s na contração.','Puxar com o ombro.','["Crucifixo","Crossover"]'::jsonb,0.9,false),
('ex_barra_fixa_pull_up','Barra fixa (pull-up)','costas','puxar vertical','peso corporal','["latíssimo","romboides","bíceps"]'::jsonb,'Pegada pronada além dos ombros, puxe até o queixo passar a barra.','Puxa com os cotovelos pra baixo; peito pra barra.','Balançar / meia amplitude.','["Pull-up supinada (chin-up)","Puxada na máquina","Barra assistida"]'::jsonb,1.3,true),
('ex_puxada_frontal_na_polia','Puxada frontal na polia','costas','puxar vertical','cabo','["latíssimo","romboides","bíceps"]'::jsonb,'Sentado, puxe a barra até a parte alta do peito, cotovelos pra baixo.','Peito aberto; não jogue o tronco.','Puxar na nuca / usar impulso.','["Puxada supinada","Puxada triângulo"]'::jsonb,1.2,false),
('ex_remada_curvada_com_barra','Remada curvada com barra','costas','puxar horizontal','barra','["latíssimo","romboides","trapézio","posterior"]'::jsonb,'Tronco inclinado ~45°, puxe a barra ao umbigo, cotovelos rentes.','Coluna neutra; puxa com as costas, não os braços.','Arredondar a lombar.','["Remada pendlay","Remada pegada supinada"]'::jsonb,1.3,false),
('ex_remada_unilateral_com_halter','Remada unilateral com halter','costas','puxar horizontal','halter','["latíssimo","romboides"]'::jsonb,'Apoio no banco, puxe o halter ao quadril, cotovelo colado.','Puxa o cotovelo pra trás e cima; contrai a escápula.','Rotacionar o tronco pra levantar mais peso.','["Remada serrote","Remada na máquina"]'::jsonb,1.1,false),
('ex_remada_baixa_na_polia','Remada baixa na polia','costas','puxar horizontal','cabo','["latíssimo","romboides","trapézio médio"]'::jsonb,'Sentado, puxe o triângulo ao abdômen, peito aberto.','Escápulas juntam no final; tronco estável.','Balançar pra frente e trás.','["Remada com corda","Remada barra reta"]'::jsonb,1.1,false),
('ex_pulldown_com_braco_reto','Pulldown com braço reto','costas','isolado','cabo','["latíssimo"]'::jsonb,'Em pé, braços retos, empurre a barra até as coxas em arco.','Isola o dorsal sem bíceps.','Dobrar o cotovelo (vira tríceps).','["Pullover com halter"]'::jsonb,0.9,false),
('ex_levantamento_terra','Levantamento terra','costas','dobrar quadril','barra','["eretores","glúteo","posterior","trapézio","latíssimo"]'::jsonb,'Barra no meio do pé, coluna neutra, empurre o chão e estenda o quadril.','Peito alto, barra colada; quadril e ombro sobem juntos.','Arredondar a lombar / puxar com as costas.','["Terra romeno","Terra sumô","Terra com trap bar"]'::jsonb,1.4,false),
('ex_encolhimento_trapezio','Encolhimento (trapézio)','costas','isolado','halter','["trapézio superior"]'::jsonb,'Em pé com halteres, encolha os ombros em direção às orelhas.','Segura 1s no topo; sem rodar os ombros.','Rodar os ombros (desgasta articulação).','["Encolhimento na barra","Encolhimento na máquina"]'::jsonb,0.9,true),
('ex_desenvolvimento_com_barra','Desenvolvimento com barra','ombro','empurrar vertical','barra','["deltoide","tríceps","trapézio"]'::jsonb,'Sentado ou em pé, barra na altura do queixo, empurre acima da cabeça.','Core firme; não hiperestenda a lombar.','Arquear demais as costas.','["Desenvolvimento halteres","Push press"]'::jsonb,1.3,false),
('ex_desenvolvimento_com_halteres','Desenvolvimento com halteres','ombro','empurrar vertical','halter','["deltoide","tríceps"]'::jsonb,'Sentado, halteres na linha das orelhas, empurre juntando levemente em cima.','Amplitude completa; punhos neutros.','Bater os halteres e perder tensão.','["Arnold press","Desenvolvimento máquina"]'::jsonb,1.2,false),
('ex_elevacao_lateral','Elevação lateral','ombro','isolado','halter','["deltoide medial"]'::jsonb,'Em pé, eleve os halteres até a linha dos ombros, cotovelo levemente flexionado.','Lidera com o cotovelo; sem impulso.','Balançar o corpo / subir com trapézio.','["Elevação na polia","Elevação na máquina"]'::jsonb,0.9,true),
('ex_elevacao_frontal','Elevação frontal','ombro','isolado','halter','["deltoide anterior"]'::jsonb,'Eleve o halter à frente até a altura dos olhos.','Controla a descida; tronco estável.','Usar embalo do quadril.','["Elevação com anilha","Elevação na polia"]'::jsonb,0.9,true),
('ex_crucifixo_invertido_rear_delt','Crucifixo invertido (rear delt)','ombro','isolado','halter','["deltoide posterior","romboides"]'::jsonb,'Tronco inclinado, abra os halteres em arco apertando as escápulas.','Foco no deltoide posterior; sem trapézio.','Usar peso demais e virar remada.','["Rear delt na polia","Peck deck invertido"]'::jsonb,0.9,true),
('ex_face_pull','Face pull','ombro','puxar horizontal','cabo','["deltoide posterior","trapézio médio","rotadores"]'::jsonb,'Corda na altura do rosto, puxe separando as mãos rumo às orelhas.','Ótimo corretivo postural; cotovelos altos.','Puxar baixo (vira remada).','["Face pull com elástico"]'::jsonb,0.9,true),
('ex_arnold_press','Arnold press','ombro','empurrar vertical','halter','["deltoide","tríceps"]'::jsonb,'Comece com palmas pra você, gire enquanto empurra acima.','Rotação suave; ativa 3 porções do ombro.','Girar rápido demais.','["Desenvolvimento halteres"]'::jsonb,1.1,false),
('ex_rosca_direta_com_barra','Rosca direta com barra','biceps','isolado','barra','["bíceps braquial"]'::jsonb,'Em pé, cotovelos fixos, flexione a barra até o peito.','Cotovelos colados ao tronco; sem embalo.','Balançar o corpo pra subir.','["Rosca W","Rosca na polia"]'::jsonb,1,true),
('ex_rosca_alternada_com_halteres','Rosca alternada com halteres','biceps','isolado','halter','["bíceps braquial","braquial"]'::jsonb,'Alterne flexionando cada halter, girando o punho (supinação).','Supina no meio do movimento.','Girar o ombro pra ajudar.','["Rosca simultânea","Rosca concentrada"]'::jsonb,0.95,true),
('ex_rosca_martelo','Rosca martelo','biceps','isolado','halter','["braquiorradial","bíceps"]'::jsonb,'Punhos neutros (martelo), flexione mantendo os polegares pra cima.','Trabalha o braquial e antebraço.','Cotovelo indo pra frente.','["Rosca martelo na corda"]'::jsonb,0.95,true),
('ex_rosca_scott','Rosca scott','biceps','isolado','barra','["bíceps"]'::jsonb,'Braços apoiados no banco scott, flexione sem tirar os cotovelos.','Isola o bíceps; não estenda totalmente sob carga.','Tirar os cotovelos do apoio.','["Rosca scott na máquina","Rosca scott halter"]'::jsonb,1,false),
('ex_rosca_concentrada','Rosca concentrada','biceps','isolado','halter','["bíceps (pico)"]'::jsonb,'Sentado, cotovelo na coxa, flexione concentrando no pico.','Segura 1s no topo.','Usar o ombro pra levantar.','["Rosca na polia baixa"]'::jsonb,0.9,true),
('ex_rosca_na_polia','Rosca na polia','biceps','isolado','cabo','["bíceps"]'::jsonb,'Barra na polia baixa, flexione com tensão constante.','Tensão contínua no bíceps.','Cotovelos abrindo.','["Rosca corda","Rosca unilateral polia"]'::jsonb,0.9,false),
('ex_triceps_na_polia_corda','Tríceps na polia (corda)','triceps','isolado','cabo','["tríceps"]'::jsonb,'Corda na polia alta, estenda separando as pontas embaixo.','Cotovelos colados; abre a corda no fim.','Mover os cotovelos pra frente.','["Tríceps barra reta","Tríceps unilateral"]'::jsonb,0.95,false),
('ex_triceps_testa','Tríceps testa','triceps','isolado','barra','["tríceps"]'::jsonb,'Deitado, desça a barra à testa flexionando só os cotovelos.','Cotovelos apontando ao teto e fixos.','Abrir os cotovelos / mexer o ombro.','["Tríceps testa halteres","Tríceps francês"]'::jsonb,1,false),
('ex_triceps_frances','Tríceps francês','triceps','isolado','halter','["tríceps (cabeça longa)"]'::jsonb,'Halter atrás da cabeça, estenda acima sem abrir os cotovelos.','Alonga a cabeça longa do tríceps.','Cotovelos abrindo demais.','["Tríceps francês na polia"]'::jsonb,0.95,true),
('ex_mergulho_entre_bancos','Mergulho entre bancos','triceps','empurrar vertical','peso corporal','["tríceps","peitoral inferior"]'::jsonb,'Mãos no banco atrás, desça o quadril e empurre.','Cotovelos pra trás; ombros longe das orelhas.','Descer demais (estresse no ombro).','["Mergulho nas paralelas"]'::jsonb,1,true),
('ex_mergulho_nas_paralelas','Mergulho nas paralelas','triceps','empurrar vertical','peso corporal','["tríceps","peitoral inferior","deltoide"]'::jsonb,'Nas barras paralelas, desça o corpo e empurre até estender.','Tronco vertical foca tríceps; inclinado foca peito.','Descer além do confortável do ombro.','["Mergulho assistido"]'::jsonb,1.2,true),
('ex_triceps_coice','Tríceps coice','triceps','isolado','halter','["tríceps"]'::jsonb,'Tronco inclinado, cotovelo alto, estenda o halter pra trás.','Cotovelo parado; contrai no fim.','Balançar o braço.','["Coice na polia"]'::jsonb,0.85,true),
('ex_agachamento_livre','Agachamento livre','pernas','agachar','barra','["quadríceps","glúteo","adutores","core"]'::jsonb,'Barra no trapézio, desça o quadril abaixo do joelho, empurre o chão.','Joelhos na direção dos pés; peito alto.','Joelho pra dentro / calcanhar subindo.','["Agachamento frontal","Agachamento box"]'::jsonb,1.4,false),
('ex_agachamento_frontal','Agachamento frontal','pernas','agachar','barra','["quadríceps","core"]'::jsonb,'Barra na frente dos ombros, cotovelos altos, agache ereto.','Tronco mais vertical; foca quadríceps.','Cotovelos caindo.','["Agachamento goblet"]'::jsonb,1.3,false),
('ex_leg_press','Leg press','pernas','agachar','maquina','["quadríceps","glúteo"]'::jsonb,'Pés na plataforma, desça até ~90° e empurre sem travar.','Não deixe a lombar sair do apoio.','Descer demais e arredondar a lombar.','["Leg press unilateral","Hack squat"]'::jsonb,1.2,false),
('ex_hack_squat','Hack squat','pernas','agachar','maquina','["quadríceps","glúteo"]'::jsonb,'Ombros na almofada, desça controlado e empurre.','Ótimo pra quadríceps com coluna apoiada.','Joelho pra dentro.','["Agachamento pêndulo"]'::jsonb,1.2,false),
('ex_cadeira_extensora','Cadeira extensora','pernas','extensao joelho','maquina','["quadríceps"]'::jsonb,'Sentado, estenda os joelhos até quase travar, controle a volta.','Segura 1s em cima; sem impulso.','Chutar o peso (impulso).','["Extensora unilateral"]'::jsonb,0.9,false),
('ex_afundo_passada','Afundo (passada)','pernas','agachar','halter','["quadríceps","glúteo"]'::jsonb,'Passo à frente, desça o joelho de trás quase ao chão, volte.','Tronco ereto; joelho alinhado ao pé.','Passo curto (joelho passa muito o pé).','["Afundo búlgaro","Passada andando"]'::jsonb,1.2,true),
('ex_agachamento_bulgaro','Agachamento búlgaro','pernas','agachar','halter','["quadríceps","glúteo"]'::jsonb,'Pé de trás no banco, desça a perna da frente e suba.','Foco unilateral e glúteo; controle.','Empurrar com a perna de trás.','["Búlgaro com barra"]'::jsonb,1.2,true),
('ex_agachamento_goblet','Agachamento goblet','pernas','agachar','halter','["quadríceps","glúteo","core"]'::jsonb,'Segure o halter no peito, agache ereto abrindo os joelhos.','Ótimo pra aprender o padrão.','Cair pra frente.','["Agachamento com kettlebell"]'::jsonb,1.1,true),
('ex_stiff_terra_romeno','Stiff (terra romeno)','posterior','dobrar quadril','barra','["posterior de coxa","glúteo","eretores"]'::jsonb,'Joelhos leves, empurre o quadril pra trás descendo a barra colada.','Sente o alongamento do posterior; coluna neutra.','Dobrar o joelho / arredondar a lombar.','["Stiff com halteres","RDL unilateral"]'::jsonb,1.3,false),
('ex_mesa_flexora','Mesa flexora','posterior','flexao joelho','maquina','["posterior de coxa"]'::jsonb,'Deitado, flexione os joelhos trazendo o calcanhar ao glúteo.','Controla a volta; quadril no apoio.','Levantar o quadril pra ajudar.','["Flexora sentado","Flexora unilateral"]'::jsonb,0.9,false),
('ex_cadeira_flexora_sentado','Cadeira flexora sentado','posterior','flexao joelho','maquina','["posterior de coxa"]'::jsonb,'Sentado, flexione os joelhos contra a almofada.','Ótimo alongamento do posterior.','Impulso com o tronco.','["Mesa flexora"]'::jsonb,0.9,false),
('ex_elevacao_pelvica_hip_thrust','Elevação pélvica (hip thrust)','gluteo','dobrar quadril','barra','["glúteo","posterior"]'::jsonb,'Costas no banco, barra no quadril, empurre até estender o quadril.','Aperta o glúteo no topo; queixo pra baixo.','Hiperestender a lombar em vez do quadril.','["Ponte de glúteo","Hip thrust unilateral"]'::jsonb,1.2,false),
('ex_ponte_de_gluteo','Ponte de glúteo','gluteo','dobrar quadril','peso corporal','["glúteo","posterior"]'::jsonb,'Deitado, pés no chão, eleve o quadril apertando o glúteo.','Contrai no topo; sem arquear a lombar.','Subir com a lombar.','["Ponte unilateral","Hip thrust"]'::jsonb,0.9,true),
('ex_cadeira_abdutora','Cadeira abdutora','gluteo','isolado','maquina','["glúteo médio"]'::jsonb,'Sentado, abra as pernas contra a almofada.','Foca o glúteo médio; controle.','Usar impulso do tronco.','["Abdução na polia","Abdução com elástico"]'::jsonb,0.85,false),
('ex_coice_na_polia_gluteo','Coice na polia (glúteo)','gluteo','dobrar quadril','cabo','["glúteo"]'::jsonb,'Caneleira na polia, estenda o quadril pra trás.','Aperta o glúteo; sem arquear a lombar.','Arquear a lombar pra subir mais.','["Coice no solo (4 apoios)"]'::jsonb,0.85,false),
('ex_panturrilha_em_pe','Panturrilha em pé','panturrilha','isolado','maquina','["gastrocnêmio"]'::jsonb,'Em pé, eleve os calcanhares ao máximo e desça alongando.','Amplitude total; pausa em cima e embaixo.','Reps rápidas sem amplitude.','["Panturrilha no smith","Panturrilha com halteres"]'::jsonb,0.85,true),
('ex_panturrilha_sentado','Panturrilha sentado','panturrilha','isolado','maquina','["sóleo"]'::jsonb,'Sentado, joelho flexionado, eleve os calcanhares.','Foca o sóleo (joelho dobrado).','Meia amplitude.','["Panturrilha no leg press"]'::jsonb,0.85,false),
('ex_panturrilha_no_leg_press','Panturrilha no leg press','panturrilha','isolado','maquina','["gastrocnêmio","sóleo"]'::jsonb,'Pés na base da plataforma, empurre com a ponta dos pés.','Controle na descida; alonga embaixo.','Travar o joelho.','["Panturrilha em pé"]'::jsonb,0.85,false),
('ex_prancha','Prancha','core','core','peso corporal','["reto abdominal","transverso","lombar"]'::jsonb,'Apoio nos antebraços e pés, corpo reto, segure contraindo o abdômen.','Glúteo e abdômen firmes; quadril na linha.','Cair o quadril / levantar demais.','["Prancha lateral","Prancha com toque no ombro"]'::jsonb,0.9,true),
('ex_abdominal_supra','Abdominal supra','core','core','peso corporal','["reto abdominal"]'::jsonb,'Deitado, joelhos dobrados, suba o tronco tirando as escápulas.','Sobe com o abdômen, não com o pescoço.','Puxar a nuca com as mãos.','["Abdominal na polia","Crunch na máquina"]'::jsonb,0.8,true),
('ex_elevacao_de_pernas','Elevação de pernas','core','core','peso corporal','["abdômen inferior","flexores do quadril"]'::jsonb,'Deitado ou pendurado, suba as pernas controlando.','Não arqueie a lombar; controle a descida.','Balançar as pernas.','["Elevação na barra","Joelho ao peito"]'::jsonb,0.9,true),
('ex_prancha_lateral','Prancha lateral','core','core','peso corporal','["oblíquos","transverso"]'::jsonb,'Apoio num antebraço, corpo lateral reto, segure.','Quadril elevado; linha reta.','Cair o quadril.','["Prancha lateral com elevação"]'::jsonb,0.85,true),
('ex_rotacao_pallof_press','Rotação (pallof press)','core','core','cabo','["oblíquos","transverso"]'::jsonb,'Cabo ao lado, empurre à frente resistindo à rotação.','Anti-rotação; core firme.','Deixar o tronco girar.','["Pallof com elástico"]'::jsonb,0.85,true),
('ex_abdominal_na_polia','Abdominal na polia','core','core','cabo','["reto abdominal"]'::jsonb,'Ajoelhado, corda na nuca, encurte o abdômen puxando pra baixo.','Enrola a coluna; quadril fixo.','Puxar com os braços/quadril.','["Crunch na máquina"]'::jsonb,0.85,false)
on conflict (id) do nothing;
